### ISSUE TITLE
REDScript compilation error

### ISSUE THREAD

**Issue by Speedoggo7** [psiberx/cp2077-equipment-ex#15]
I install all the dependencies, and I make sure everything is up to date but I still get this error
![Screenshot 2023-02-28 205943](https://user-images.githubusercontent.com/126643892/222048858-cefa9e49-5ab2-40cf-bf05-c0552704452c.png)

**Comment by psiberx** [comment]
This is not an Equipment-EX issue. 
Follow FAQ https://www.nexusmods.com/cyberpunk2077/mods/6945?tab=posts
