### ISSUE TITLE
Equipment-EX related crash with "Nylon Pantyhose and Tights for V" mod.

### ISSUE THREAD

**Issue by icywinter** [psiberx/cp2077-equipment-ex#18]
I have a bug regarding the interactions between Equipment-EX and "Nylon Pantyhose and Tights for V". [The mod link can be found here.](https://www.nexusmods.com/cyberpunk2077/mods/12076)

I have confirmed that it is Equipment-EX that is causing a CTD, not the clothing mod. The process to reproduce the crash is listed below.

0. Progress the game to when Reed tells the player to meet with Farida.
1. Travel to Farida's clinic in Dogtown.
2. Equip the pantyhose through Equipment-EX. This can be any of the pantyhose/tights.
3. Talk to Farida through the intercom.

The game will crash as soon as V introduces themselves.

The game does not crash when the player disables Equipment-EX's transmog and equips the pantyhose in the lower-leg slot.

Moreover, each attch text file details that the game crashed because the thread is attempting to read inaccessible data at 0x1EC.

> Registered crash info file...
InternalVersion: 3.0.4984974  P4CL: 6525662  Stream: //R6.Root/R6.Release
!!!CRASHED!!!
Error Reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x1EC.
File: <Unknown>
Line: 0

I've tested all of the pantyhose variations and they all have the same crash reason.

I am currently running the latest versions of all of the dependencies, the latest version of Equipment-EX, and I am using the latest version of the mod for Hyst Big Booty, however another mod user reported the same issue on the vanilla version as well.

I can provide the crash logs if necessary.

**Comment by psiberx** [comment]
Hi. Please share your save file before the crash and crash report (with dump file).

**Comment by psiberx** [comment]
Fixed in ArchiveXL 1.10.4.
