### ISSUE TITLE
Lack of install instructions and How to Use instructions

### ISSUE THREAD

**Issue by webravager** [psiberx/cp2077-equipment-ex#4]
Kwek is a creator on Nexus for CP2077 Mods and they keep referring to this tool/mod and offer some of their clothing with files related to Equipment EX and provided a link to this site, I am having issues determining exactly how to install and use this in CP2077. I extract the Zip and nowhere in the Readme doc or on this site does it explain exactly how to install and use this.
I thought at first that I simply drop the cp2077-equipment-ex-master folder into the C:\Games\Steam\steamapps\common\Cyberpunk 2077\mods folder but that doesn't seem to do anything at all. Do I drop the contents of the folder into the CP2077 root folder?

**Comment by webravager** [comment]
Edit: I think I figured out where to put the files.. for me it is in the C:\Games\Steam\steamapps\common\Cyberpunk 2077\r6\scripts\cp2077-equipment-ex-master 
In game I now have a 'Wardrobe' button in the Inventory Screen that wasn't there before, but it is empty when I click on it. I do have some content installed from Kwek that should be showing up I thought but apparently there are additional steps to get things to show there. Please advise.

**Comment by psiberx** [comment]
First of all, this mod is in development and hasn't been released yet.
General advice for GitHub: download releases, not source code, if you just want to use it, not develop.

**Comment by psiberx** [comment]
How to use instructions are available on the community Discord, where the pre-release was officially posted.
