### ISSUE TITLE
REDScript Error on 0.7.6

### ISSUE THREAD

**Issue by webravager** [psiberx/cp2077-equipment-ex#5]
<img width="418" alt="REDScript error" src="https://user-images.githubusercontent.com/56234671/210150570-fb2f3ce1-807b-4943-99a4-bc624f69b13f.png">

**Comment by psiberx** [comment]
Do a clean install.

**Comment by BanthaFood** [comment]
No. Just remove every file of equipment-ex and install the mod again. (if that wasn't what you meant. I thought you meant a clean install of the game)

**Comment by psiberx** [comment]
I meant clean install of the mod. You should do it every update.

**Comment by dnielsen1980** [comment]
This is my first time installing, and I got the same redscript error as above. I've tried both manual install, and dropping into Vortex.
