### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Virtual-Chris** [psiberx/cp2077-equipment-ex#9]
Issues: 
- Several clothing items show as having a "REQ" for 1 level higher than my current level but can be applied anyway
- Some items are not available such as these... https://www.nexusmods.com/cyberpunk2077/mods/3041
- This item is also not showing up despite being specifically designed for this... https://www.nexusmods.com/cyberpunk2077/mods/6958?tab=description

All pre-requisites updated to the latest versions from Github.

Shot showing the glove mod not showing... https://live.staticflickr.com/65535/52606366268_2b959b5517_k.jpg

**Comment by psiberx** [comment]
- It's expected behavior for any requirements and transmog system. Maybe we'll hide REQ info to reduce confusion.
- It's up to the author of the item to make them compatible with the mod. But as for the two mods you mentioned: they both work perfectly with Equipment-EX.

**Comment by psiberx** [comment]
If you need help with your mods setup it's better to use Discord or Nexus.

**Comment by Virtual-Chris** [comment]
Thanks. I got the 3rd bullet resolved, that was my bad. I have no idea why the 2nd bullet mods are not showing in my wardrobe... I had them installed and are in use on some of my outfits.  So they are showing on my character when I select the old outfit, but the individual items are not showing in my inventory. Do I need to re-install them or activate the whole historical wardrove inventory in the mods options?

**Comment by psiberx** [comment]
The mod was published on Nexus just a couple of hours ago.
